export const FETCH_TEST_REQUEST = 'FETCH_TEST_REQUEST'
export const FETCH_TEST_SUCCESS = 'FETCH_TEST_SUCCESS'
export const FETCH_TEST_FAILED = 'FETCH_TEST_FAILED'

export const FETCH_USER_REQUEST = 'FETCH_USER_REQUEST'
export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS'
export const FETCH_USER_FAILED = 'FETCH_USER_FAILED'

export const FETCH_200_REQUEST = 'FETCH_200_REQUEST'
export const FETCH_200_SUCCESS = 'FETCH_200_SUCCESS'
export const FETCH_200_FAILED = 'FETCH_200_FAILED'
